columns:
  - complaint_id: object
  - timestamp: object
  - crime_type: object
  - amount_lost: float64
  - urgency_level: object
  - complaint_city: object
  - complaint_state: object
  - complaint_lat: float64
  - complaint_lng: float64
  - victim_phone: object
  - predicted_withdrawal_lat: float64
  - predicted_withdrawal_lng: float64
  - withdrawal_probability: float64
  - risk_score: float64
  - status: object
  - reported_by: object
  - investigation_officer: object
  - bank_involved: object
  - distance_km: float64
  - alert_priority: object
  - hour: int64
  - day_of_week: int64
  - is_weekend: bool
  - is_peak_hours: bool

numerical_columns:
  # Amount and Geographic
  - amount_lost
  - complaint_lat
  - complaint_lng
  - predicted_withdrawal_lat
  - predicted_withdrawal_lng
  - withdrawal_probability
  - risk_score
  - distance_km
  - hour
  - day_of_week

categorical_columns:
  - crime_type
  - urgency_level
  - complaint_city
  - complaint_state
  - status
  - reported_by
  - investigation_officer
  - bank_involved
  - alert_priority
  - is_weekend
  - is_peak_hours

target_variables:
  - withdrawal_probability
  - risk_score

feature_columns:
  - amount_lost
  - complaint_lat
  - complaint_lng
  - crime_type
  - urgency_level
  - complaint_city
  - complaint_state
  - distance_km
  - alert_priority
  - hour
  - day_of_week
  - is_weekend
  - is_peak_hours